# Generated by Django 5.2.7 on 2025-11-04 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LatihanSoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PertanyaanPengayaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_pertanyaan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SoalPengayaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default='Ujian Akhir Bab', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubBab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('urutan', models.IntegerField(help_text='Urutan bab, e.g., 1, 2, 3', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HasilLatihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('latihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.latihansoal')),
            ],
        ),
        migrations.CreateModel(
            name='Pertanyaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_pertanyaan', models.TextField()),
                ('latihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertanyaan_set', to='main.latihansoal')),
            ],
        ),
        migrations.CreateModel(
            name='PilihanJawaban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_pilihan', models.CharField(max_length=200)),
                ('is_benar', models.BooleanField(default=False)),
                ('pertanyaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilihan_set', to='main.pertanyaan')),
            ],
        ),
        migrations.CreateModel(
            name='JawabanSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_benar', models.BooleanField()),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pertanyaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pertanyaan')),
                ('pilihan_dipilih', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pilihanjawaban')),
            ],
        ),
        migrations.CreateModel(
            name='PilihanPengayaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_pilihan', models.CharField(max_length=200)),
                ('is_benar', models.BooleanField(default=False)),
                ('pertanyaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilihan_set', to='main.pertanyaanpengayaan')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SISWA', 'Siswa'), ('GURU', 'Guru')], max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pertanyaanpengayaan',
            name='pengayaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertanyaan_set', to='main.soalpengayaan'),
        ),
        migrations.CreateModel(
            name='HasilPengayaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pengayaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.soalpengayaan')),
            ],
        ),
        migrations.AddField(
            model_name='latihansoal',
            name='subbab',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.subbab'),
        ),
        migrations.CreateModel(
            name='ProgressSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modul_completed', models.BooleanField(default=False)),
                ('latihan_completed', models.BooleanField(default=False)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subbab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subbab')),
            ],
            options={
                'unique_together': {('siswa', 'subbab')},
            },
        ),
    ]
