# Generated by Django 5.2.7 on 2025-11-04 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiswaProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modul_1_completed', models.BooleanField(default=False)),
                ('latihan_1_completed', models.BooleanField(default=False)),
                ('glosarium_completed', models.BooleanField(default=False)),
                ('modul_2_completed', models.BooleanField(default=False)),
                ('latihan_2_completed', models.BooleanField(default=False)),
                ('mikroskop_completed', models.BooleanField(default=False)),
                ('database_completed', models.BooleanField(default=False)),
                ('modul_3_completed', models.BooleanField(default=False)),
                ('latihan_3_completed', models.BooleanField(default=False)),
                ('pengayaan_completed', models.BooleanField(default=False)),
                ('siswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ProgressSiswa',
        ),
    ]
