# Generated by Django 5.2.7 on 2025-11-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_siswaprogress_delete_progresssiswa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pertanyaan',
            name='explanation',
            field=models.TextField(blank=True, help_text='Penjelasan/Feedback untuk jawaban yang benar', null=True),
        ),
        migrations.AddField(
            model_name='pertanyaanpengayaan',
            name='explanation',
            field=models.TextField(blank=True, help_text='Penjelasan/Feedback untuk jawaban yang benar', null=True),
        ),
    ]
