# Generated by Django 5.2.7 on 2025-11-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pertanyaan_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pertanyaanpengayaan',
            name='kunci_jawaban_isian',
            field=models.CharField(blank=True, help_text='Isi kunci jawaban di sini jika tipe soal adalah Isian (tidak case-sensitive).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pertanyaanpengayaan',
            name='tipe',
            field=models.CharField(choices=[('PG', 'Pilihan Ganda'), ('ISIAN', 'Isian Singkat')], default='PG', max_length=10),
        ),
    ]
